### ISSUE TITLE
Issue with button-editable

### ISSUE THREAD

**Issue by manishsongirkar** [rtCamp/gutenberg-fields-middleware#30]
1. Not able to set dynamic background color and text color using editable button. I also checked with this [example](https://github.com/rtCamp/gutenberg-fields-middleware#updating-field-props) . This only works with button but not button-editable.
2. If user navigate using tab, then not able to add text or link.

**Comment by sayedtaqui** [comment]
Fixed in https://github.com/rtCamp/gutenberg-fields-middleware/commit/b3590cf21a26299554ca4632d800cdd77ded1bdb
