### ISSUE TITLE
What version of Gutenberg does this work with?

### ISSUE THREAD

**Issue by jasonbahl** [rtCamp/gutenberg-fields-middleware#49]
I've tried this with Gutenberg versions 2.2-2.7 and can't get it to work with any of them. 

## Steps to Reproduce
- activate Gutenberg v2.2 - 2.7
- activate gutenberg-fields-middleware
- create new post
- try to add "Simple Example Block" to the post
- check your console

This is what I'm seeing, for the most part. . .varies a bit based on the version of Gutenberg:

![screen shot 2018-04-23 at 11 55 18 am](https://user-images.githubusercontent.com/1260765/39144202-5190d8ae-46ed-11e8-9bdd-0a876344754d.png)
![screen shot 2018-04-23 at 11 55 23 am](https://user-images.githubusercontent.com/1260765/39144203-51a18960-46ed-11e8-9079-63af8670d6a2.png)

**Comment by yahilmadakiya** [comment]
@jasonbahl Working fine for me.
I have tested with
`Wordpress: 4.9.5`
`Gutenberg: 2.7.0`
`Chrome Browser: 60.0.3112.113 (64-bit)`

Can you please check with `gutenberg-fields-middleware` latest code? You can download that [here](https://github.com/rtCamp/gutenberg-fields-middleware/archive/develop.zip).

![49](https://user-images.githubusercontent.com/11607839/39145175-904adf8c-4750-11e8-839b-03640fb9c2cc.png)

**Comment by sayedtaqui** [comment]
Thanks for trying it @jasonbahl , can you please tell me if you are using any other plugin which has gutenberg blocks?

**Comment by jasonbahl** [comment]
@sayedtaqui blaming my environment for this one. Things are working fine for me now.

**Comment by sayedtaqui** [comment]
@jasonbahl If you could share anything about your env setup, I was really curious to know what might conflict with the middleware. That would be very helpful to me.

**Comment by jasonbahl** [comment]
@sayedtaqui I was using Yoast SEO, Atomic Blocks and some custom blocks I'm working on. . .I assumed it was a conflict with one of those plugins, so i de-activated everything but Gutenberg and your plugin and the issue still was there. 

I tried on a different environment completely, and things work now. 

I was using wp-local-docker (https://github.com/10up/wp-local-docker) for my local environment, and now I'm using Local by Flywheel. 

Not sure _why_ my local environment would make much difference here, but seems like the switch fixed things.

**Comment by sayedtaqui** [comment]
@jasonbahl I will try that env locally later sometime and see if there is anything I can do to improve in middleware to not have that conflict. Thanks for the detail.

**Comment by jasonbahl** [comment]
Sweet. Thanks! I really love this middleware idea. I’m working on a similar idea for WPGraphQL + Gutenberg where you will be able to register a GraphQL query with your block to be used as the datasource. Kinda hard to explain right now unless you’re familiar with GraphQL. 


Either way, great work here!
