### ISSUE TITLE
Server Side Registration not working

### ISSUE THREAD

**Issue by jasonbahl** [rtCamp/gutenberg-fields-middleware#52]
Hey, I've got things working well for Client Side registration, but I'm not able to see blocks registered server side. 

Using your example: 

```
register_block_type( 'example-namespace/example-block', array(
        'title' => 'Example Block',
	'attributes' => array(
		'image' => array(
			'type' => 'object',
			'field' => array(
				'type' => 'image',
				'buttonText' => 'Upload',
				'imagePlaceholder' => true,
				'removeButtonText' => 'Remove',
			),
		),
		'color' => array(
			'type' => 'string',
			'field' => array(
				'type' => 'color'
			)
		)
	),
	'render_callback' => 'example_callback',
) );
```

I don't have an `example block` in my list of blocks. 

I know Gutenberg support for Server Side registry is pretty weak. . .not sure if this is still a limitation of Gutenberg, an issue with this plugin, or just something I'm doing wrong?

**Comment by sayedtaqui** [comment]
Middleware does not do server side registration however by
> ✔️ Gutenberg Fields Middleware also works for PHP block registration:

we meant that the `field` would also work when you do server side registration. I think the sentence looks confusing, I will update that in readme. The minimum that needs to be done in JS is to register the block like this 
```js
wp.blocks.registerBlockType( 'gb-m-example/simple-block-server-side', {} );
```
I added an example of it in `examples/` folder. https://github.com/rtCamp/gutenberg-fields-middleware/tree/develop/examples/server-side-registration

**Comment by jasonbahl** [comment]
Thanks for the quick reply. I’ll check this out and report back. 

Thanks!

**Comment by jasonbahl** [comment]
@sayedtaqui this still doesn't work. 

Using the example, I still don't have the "Example Block Server Side" showing in the inserter. 

I do see it getting localized to the `window. _wpBlocks` but it looks like Gutenberg isn't taking that and using it in the UI 🤔 

<img width="551" alt="screen shot 2018-04-25 at 7 33 25 am" src="https://user-images.githubusercontent.com/1260765/39254904-7b7cdcd6-4868-11e8-8a84-45cbe933f57f.png">
<img width="636" alt="screen shot 2018-04-25 at 7 34 01 am" src="https://user-images.githubusercontent.com/1260765/39254907-7b975714-4868-11e8-9549-50e34cceb14d.png">

**Comment by sayedtaqui** [comment]
@jasonbahl  This is strange, have you tried with just gutenberg and middleware plugins activated?

![server-side-registration](https://user-images.githubusercontent.com/6297436/39260500-591a8728-48d7-11e8-8390-a9a800cda88a.gif)

**Comment by sayedtaqui** [comment]
@jasonbahl I also tried with Yoast SEO and Atomic Blocks plugin activated, didn't see any conflict. Don't know what would could have caused conflict in your setup.

![image](https://user-images.githubusercontent.com/6297436/39260942-8674b828-48d8-11e8-8cd1-1659132cc029.png)

**Comment by jasonbahl** [comment]
@sayedtaqui aha!

Figured it out!

So, I had a block edit: function registered on the client, and it was just returning a component. . .I needed to also return `props.middleware.inspectorControls` to the return statement.
