### ISSUE TITLE
Do a final review of everything before tagging release

### ISSUE THREAD

**Issue by danielbachhuber** [rtCamp/gutenberg-fields-middleware#6]

**Comment by danielbachhuber** [comment]
@sayedtaqui I did a [pretty substantial rewrite](https://github.com/rtCamp/gutenberg-fields-middleware#gutenberg-fields-middleware) of the README intro. Does everything seem reasonable to you?

I think it'd make sense to reformat the `Available Fields` section at some point, but what we have is good enough for the first release.

**Comment by sayedtaqui** [comment]
@danielbachhuber Looking good.
Just this example does not tell how to use the fields inside `edit` method.
```js
registerBlockType( 'example-namespace/example-block', {
	title: 'Example Block',
	url: {
		type: 'string',
		field: {
			type: 'url',
		},
	},
	text: {
		type: 'string',
		field: {
			type: 'text',
			placeholder: 'Enter link text',
		},
	},
});
```

We can either show `edit( props, middleware )` in the example or add documentation for it.

**Comment by yahilmadakiya** [comment]
`register_block_type` has `render_callback` callback function.

I think we should add `'render_callback' => 'example_callback',` with example in README.

**Comment by danielbachhuber** [comment]
@sayedtaqui @yahilmadakiya Would one of you like to submit a PR with those suggested changes?

**Comment by yahilmadakiya** [comment]
Here is the PR for the same :point_right:  https://github.com/rtCamp/gutenberg-fields-middleware/pull/21
