### ISSUE TITLE
Image field doesn't have a way to remove/replace when in the inspector

### ISSUE THREAD

**Issue by jasonbahl** [rtCamp/gutenberg-fields-middleware#61]
When using the image field in the inspector, once an image has been added, there's no option to remove it. 

```
'attributes'      => [
		'backgroundImage' => [
			'type'  => 'object',
			'field' => [
				'type'             => 'image',
				'label'            => __( 'Background Image', 'oshpd' ),
				'placement'        => 'inspector',
				'removeButtonText' => 'Remove',
			],
		],
],
```

![screen shot 2018-04-27 at 2 11 25 pm](https://user-images.githubusercontent.com/1260765/39383027-ea7ef228-4a24-11e8-9266-4dad4f7567d4.png)

**Comment by sayedtaqui** [comment]
Thanks @jasonbahl , fixed in PR#62 now showing edit icon

![image](https://user-images.githubusercontent.com/6297436/39392654-69613ab2-4ad7-11e8-8e07-440802455afd.png)
