### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by ChaosExAnima** [rtCamp/gutenberg-fields-middleware#69]
Howdy!

What license is this code released under? I see a reference to GPLv2 in the `package.json` file, but none of the usual text is present.

Thanks!

**Comment by rahul286** [comment]
@ChaosExAnima The license is included here https://github.com/rtCamp/gutenberg-fields-middleware/blob/develop/gutenberg-fields-middleware.php in line with WordPress plugin guidelines https://developer.wordpress.org/plugins/the-basics/including-a-software-license/

However, we will add a copy of license in root repo in Github style https://help.github.com/articles/adding-a-license-to-a-repository/

This plugin is GPL v2 indeed. :)
