### ISSUE TITLE
Error in wordpress 5.0.0 beta

### ISSUE THREAD

**Issue by hamedmoody** [rtCamp/gutenberg-fields-middleware#71]
Hi
I download github project and set active development mode with set IS_GUTENBERG_FIELDS_MIDDLEWARE_DEV to true to active example.
But I have just "Simple Example Block" block and have not advanced settings fields in advanced sidebar:
![image](https://user-images.githubusercontent.com/9475089/48333156-9a55bf00-e66b-11e8-84a3-9075cc2b5934.png)

I have error in console:
![image](https://user-images.githubusercontent.com/9475089/48333136-8f029380-e66b-11e8-95e4-dced2fbb5fc3.png)

**Comment by sayedtaqui** [comment]
Hi @hamedmoody, The last release code on `master` is too outdated now. Did you try the latest `develop` branch? I have yet to release a new version after testing.

**Comment by hamedmoody** [comment]
Ok i have last develop branch

**Comment by hamedmoody** [comment]
I download from here:
![image](https://user-images.githubusercontent.com/9475089/48351489-a3608380-e69f-11e8-9075-a0c7740178cf.png)

**Comment by sayedtaqui** [comment]
@hamedmoody Just tested, it doesn't work with WordPress 5.0 beta4, I think I would need to make some modification. Will do soon. Thanks!

**Comment by ajitbohra** [comment]
fixed here https://github.com/rtCamp/gutenberg-fields-middleware/pull/72

**Comment by sayedtaqui** [comment]
Fixed in v0.3.0 , closing issue.
