### ISSUE TITLE
Media Upload field is not compatible with WordPress 5.0-RC

### ISSUE THREAD

**Issue by sayedtaqui** [rtCamp/gutenberg-fields-middleware#74]
Uploading media in `media-upload` field throws the following error and needs to updated according to the latest changes in Gutenberg.

![image](https://user-images.githubusercontent.com/6297436/49099515-ac547600-f297-11e8-8922-ceab6f5c7bf9.png)

**Comment by yahilmadakiya** [comment]
Fixed in 👉 https://github.com/rtCamp/gutenberg-fields-middleware/pull/75

Colsing
